// Standard shadcn/ui button. Generated by `bunx shadcn@latest add button`
// in spirit; vendored here so the scaffold builds without that step.

import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

// Pills, hairlines, no drop shadows. Editorial restraint.
const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full text-sm font-medium transition-[opacity,background-color,color,border-color] duration-200 ease-out focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-40",
  {
    variants: {
      variant: {
        // Primary: filled accent (deep forest), pill geometry, no shadow.
        default: "bg-primary text-primary-foreground hover:opacity-90",
        // Destructive: kept for confirm/revoke flows.
        destructive: "bg-destructive text-destructive-foreground hover:opacity-90",
        // Outline = the workhorse — hairline border, ghost fill, ink text.
        outline: "border border-border bg-transparent text-foreground hover:bg-muted",
        // Secondary: subtle filled muted surface.
        secondary: "bg-muted text-foreground hover:opacity-80",
        // Ghost: no border, ink-fade hover only.
        ghost: "text-foreground hover:opacity-70",
        // Link: inline underline.
        link: "text-foreground underline-offset-4 hover:underline rounded-none px-0",
      },
      size: {
        default: "h-9 px-5 py-2",
        sm: "h-8 px-4 text-xs",
        lg: "h-10 px-7",
        icon: "h-9 w-9 rounded-full",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return <Comp ref={ref} className={cn(buttonVariants({ variant, size, className }))} {...props} />;
  },
);
Button.displayName = "Button";

export { buttonVariants };
