-- Seed: paper-games project + reddit draft set
-- Generated by api/scripts/seed-paper-games.mjs

-- 1. user (idempotent: skip if email exists)
INSERT OR IGNORE INTO users (id, email) VALUES ('019e02b3-ec81-7bd2-abfd-19c2f5bc6973', 'you@example.com');

-- 2. project (idempotent: skip if slug exists)
INSERT OR IGNORE INTO projects (id, slug, name, description, owner_id) SELECT '019e02b3-ec83-7124-a5e5-ee1db287e900', 'paper-games', 'Paper Games', 'Pen-and-paper games for iOS + Android. Free, no ads, no analytics.', id FROM users WHERE email = 'you@example.com';

-- 3. owner membership
INSERT OR REPLACE INTO project_members (project_id, user_id, role) SELECT p.id, u.id, 'owner' FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games';

-- 4. drafts (one per subreddit, idempotent on title)
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec84-7878-a085-c6dda32c9081', p.id, NULL, 'draft', 'r/iosgaming — weekly thread comment', '**Paper Games — pen-and-paper games for iOS, free, no ads**

6 games, all paper-themed: Tic-Tac-Toe, Connect Four, Dots and Boxes, plus four single-player ones. No ads, no signup, no tracking.

Demo: [imgur link to GIF]

https://install.papergames.z6o.cc/?referrer=r_iosgaming

Built solo with Expo + cached PWA. Happy to answer anything.', 'markdown', '{"subreddit":"iosgaming","postKind":"comment","seedReferrerSlug":"r_iosgaming","seedPriority":"tier_1","seedSequence":1}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'r/iosgaming — weekly thread comment');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec84-73c8-99f2-51f724d0ddc8', p.id, NULL, 'draft', 'I missed playing pen-and-paper games in the back of a notebook, so I made the notebook into an app — free, no ads, no analytics', 'I grew up playing Dots and Boxes and Tic-Tac-Toe in the margins of school notebooks. Most "paper games" mobile apps look like every other casual game — flat colors, big buttons, ads every 30 seconds.

I wanted the actual notebook. Lined paper, the red margin line, Permanent Marker font for headings. So I built it.

6 games right now: Tic-Tac-Toe, Connect Four, plus four single-player ones (Golf solitaire, a labyrinth, a dungeon crawler, a galaxy puzzle). All paper-themed. **No ads, no analytics SDKs, no accounts.** I literally don''t know who''s playing — and that''s the point.

Built solo over 8 months with Expo + a cached PWA (one codebase, both stores). Happy to nerd out on that in the comments.

📱 https://install.papergames.z6o.cc/?referrer=r_sideproject

Roast it — I want it to get better.', 'markdown', '{"subreddit":"SideProject","postKind":"self","seedReferrerSlug":"r_sideproject","seedPriority":"tier_1","seedSequence":2}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'I missed playing pen-and-paper games in the back of a notebook, so I made the notebook into an app — free, no ads, no analytics');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec84-7f19-8bad-55c6b7cbf538', p.id, NULL, 'draft', 'Made a paper-notebook themed game collection for Android — free, no ads, no signup', '6 paper-and-pencil games in one app: Tic-Tac-Toe, Connect Four, Dots and Boxes, plus 4 single-player ones (Golf solitaire, Labyrinth, Dungeon, Galaxy puzzle). All themed like an actual notebook — lined paper, red margin, marker-pen handwriting.

No ads, no signup, no analytics. Free.

https://install.papergames.z6o.cc/?referrer=r_androidgaming

Solo dev, 8 months. Built with Expo + a cached PWA so it works offline after first launch. Happy to chat in the comments.', 'markdown', '{"subreddit":"AndroidGaming","postKind":"self","seedReferrerSlug":"r_androidgaming","seedPriority":"tier_1","seedSequence":3}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Made a paper-notebook themed game collection for Android — free, no ads, no signup');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec84-7d03-93cd-8995a7d0a57e', p.id, NULL, 'draft', 'Built a free app of pen-and-paper games — same ones we all played in school notebooks', 'Hey — long-time lurker here. I always wanted a phone version of the games this sub is built around (Dots and Boxes, Tic-Tac-Toe, MASH-style stuff) that didn''t feel like every other casual mobile game.

So I built one. Six games, all paper-themed (lined paper, red margin line, marker-pen handwriting). Free, no ads, no signup, no tracking.

https://install.papergames.z6o.cc/?referrer=r_pen_and_paper_games

Would love feedback — specifically: what pen-and-paper games would you want to see added? My next batch will be whatever the sub votes for.', 'markdown', '{"subreddit":"pen_and_paper_games","postKind":"self","seedReferrerSlug":"r_pen_and_paper_games","seedPriority":"tier_2","seedSequence":4}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Built a free app of pen-and-paper games — same ones we all played in school notebooks');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7fbe-b134-631e1ab9095e', p.id, NULL, 'draft', 'Paper Games — pen-and-paper games in your browser, no ads, no signup', 'Free, runs in the browser, installable as a PWA if you want it offline. No ads, no signup, no tracking.

Tic-Tac-Toe, Connect Four, Dots and Boxes, plus four single-player games. All paper-themed.

Browser: https://papergames.z6o.cc/?referrer=r_webgames
Mobile install: https://install.papergames.z6o.cc/?referrer=r_webgames

Built solo with Vite + React. Service worker handles offline.', 'markdown', '{"subreddit":"WebGames","postKind":"self","seedReferrerSlug":"r_webgames","seedPriority":"tier_1","seedSequence":5}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Paper Games — pen-and-paper games in your browser, no ads, no signup');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7c9e-9f88-9e5379c69eb6', p.id, NULL, 'draft', 'Built a Tic-Tac-Toe app that looks like the actual notebook page you played it on', 'Made a Tic-Tac-Toe app that''s themed like an actual school notebook — lined paper, red margin line, marker-pen X''s and O''s.

Free, no ads, no signup. iOS + Android.

https://install.papergames.z6o.cc/?referrer=r_tictactoe

It''s part of a 6-game collection (also Connect Four, Dots and Boxes, etc.), but TTT is the one that started it. Solo project, happy for feedback.', 'markdown', '{"subreddit":"tictactoe","postKind":"self","seedReferrerSlug":"r_tictactoe","seedPriority":"tier_2","seedSequence":6}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Built a Tic-Tac-Toe app that looks like the actual notebook page you played it on');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7fb1-8742-c048bdd31a9d', p.id, NULL, 'draft', 'Made a Connect Four app that draws on lined paper, no ads, free', 'Free Connect Four for iOS + Android, drawn like it''s being played on graph paper. Tap a column, the disc drops with a hand-drawn ink animation.

No ads, no signup, no tracking.

https://install.papergames.z6o.cc/?referrer=r_connectfour

Part of a paper-themed bundle of 6 games. Solo dev, would love feedback specifically on the AI difficulty curve.', 'markdown', '{"subreddit":"ConnectFour","postKind":"self","seedReferrerSlug":"r_connectfour","seedPriority":"tier_2","seedSequence":7}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Made a Connect Four app that draws on lined paper, no ads, free');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7e71-99b7-6d6198075753', p.id, NULL, 'draft', 'r/incremental_games — weekly thread comment', '**Galaxy — a paper-themed exploration/collection game**

Map the galaxy on graph paper, each planet you visit reveals more of the grid. Single-player, light-progression, the whole thing fits in the back of a notebook.

Demo: [imgur GIF]

Part of a 6-game free collection — no ads, no signup. https://install.papergames.z6o.cc/?referrer=r_incremental

Solo dev, happy to chat.', 'markdown', '{"subreddit":"incremental_games","postKind":"comment","seedReferrerSlug":"r_incremental","seedPriority":"tier_1","seedSequence":8}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'r/incremental_games — weekly thread comment');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7c74-87a6-eaf705168d64', p.id, NULL, 'draft', 'Pen-and-paper games are how I learned strategy as a kid — I rebuilt the notebook for my phone', 'Before video games, my grandfather taught me Dots and Boxes on the back of restaurant placemats. I never see kids playing those games anymore — and the mobile versions of them are awful, full of ads.

So over 8 months I built a free, ad-free notebook of 6 paper-and-pencil games. Tic-Tac-Toe, Connect Four, Dots and Boxes, plus 4 single-player ones. The whole UI is drawn to look like an actual school notebook — lined paper, marker-pen ink.

Not pitching this as a board game replacement — it''s the *opposite*: a way to introduce the abstract pen-and-paper games to kids who only have screens.

https://install.papergames.z6o.cc/?referrer=r_boardgames

Curious if anyone here remembers playing these as a kid. What other pen-and-paper games would you add?', 'markdown', '{"subreddit":"boardgames","postKind":"self","seedReferrerSlug":"r_boardgames","seedPriority":"tier_2","seedSequence":9}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Pen-and-paper games are how I learned strategy as a kid — I rebuilt the notebook for my phone');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec85-7be9-ae14-d039a06748ab', p.id, NULL, 'draft', 'A digital "notebook" app I made — drawn to feel like real lined paper', 'Not strictly papercraft, but I built it because I love the look of school notebooks — lined paper, the red margin line, marker-pen handwriting. Wanted to share with a sub that appreciates the medium.

It''s a phone app of pen-and-paper games (Tic-Tac-Toe, Dots and Boxes, etc.). Free, no ads.

https://install.papergames.z6o.cc/?referrer=r_papercraft', 'markdown', '{"subreddit":"papercraft","postKind":"self","seedReferrerSlug":"r_papercraft","seedPriority":"tier_3","seedSequence":10}', u.id FROM projects p JOIN users u ON u.email = 'you@example.com' WHERE p.slug = 'paper-games'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'A digital "notebook" app I made — drawn to feel like real lined paper');

