-- Seed: tapeline (measure_app) project + Product Hunt launch drafts
-- Generated by api/scripts/seed-tapeline.mjs

-- 1. user
INSERT OR IGNORE INTO users (id, email) VALUES ('019e02b3-ec93-7947-84b4-b73b4588f2ee', 'sangeet.verma91@gmail.com');

-- 2. project
INSERT OR IGNORE INTO projects (id, slug, name, description, owner_id) SELECT '019e02b3-ec93-7391-80f8-c60b754d0c7c', 'tapeline', 'Tapeline', 'Tapeline — body measurement journal. iOS + Android. Product Hunt launch kit drafts.', id FROM users WHERE email = 'sangeet.verma91@gmail.com';

-- 3. owner membership
INSERT OR REPLACE INTO project_members (project_id, user_id, role) SELECT p.id, u.id, 'owner' FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline';

-- 4. drafts (idempotent on title)
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-7ec2-acbc-3242e4fee844', p.id, NULL, 'draft', 'T-2 — pre-launch X thread (5 tweets)', '1/ I''m launching the thing I''ve been building for 3 years on Product Hunt this Wednesday.

Quick recap of why, what, how — for the people who''ve followed along.

🧵

2/ The why:

Started lifting weights 3 years ago. Stepped on the scale every morning. Useless number. Lost 4kg one month, gained 3kg the next, body looked the same in both. The scale was lying to me.

Started using a measuring tape. The numbers told the truth.

3/ Tried 5 apps to log the measurements. Hated all of them.

One demanded my email before showing me anything. One sold the data. One had a UI from 2014. None of them compared progress photos in any usable way.

So I started building.

4/ Tapeline is the result.

30 seconds a day. Log weight + 10 body dimensions + wellness + (Pro) photos. Compare any two days side-by-side. Daily reminders that respect your timezone.

No social feed. No calorie tracker. No "share your transformation" wall.

5/ Launching Wednesday at 12:30 PM IST on @ProductHunt.

If you''ve been on this side of the timeline watching the build-in-public, the favor is small: drop a comment with your honest take. The harshest specific feedback wins a year of Pro.

Link drops Wednesday.', 'markdown', '{"seedSequence":1,"seedIntendedTime":"T-2 days, 9:00 AM IST","postKind":"thread","threadSegments":[{"text":"1/ I''m launching the thing I''ve been building for 3 years on Product Hunt this Wednesday.\n\nQuick recap of why, what, how — for the people who''ve followed along.\n\n🧵","mediaIds":[]},{"text":"2/ The why:\n\nStarted lifting weights 3 years ago. Stepped on the scale every morning. Useless number. Lost 4kg one month, gained 3kg the next, body looked the same in both. The scale was lying to me.\n\nStarted using a measuring tape. The numbers told the truth.","mediaIds":[]},{"text":"3/ Tried 5 apps to log the measurements. Hated all of them.\n\nOne demanded my email before showing me anything. One sold the data. One had a UI from 2014. None of them compared progress photos in any usable way.\n\nSo I started building.","mediaIds":[]},{"text":"4/ Tapeline is the result.\n\n30 seconds a day. Log weight + 10 body dimensions + wellness + (Pro) photos. Compare any two days side-by-side. Daily reminders that respect your timezone.\n\nNo social feed. No calorie tracker. No \"share your transformation\" wall.","mediaIds":[]},{"text":"5/ Launching Wednesday at 12:30 PM IST on @ProductHunt.\n\nIf you''ve been on this side of the timeline watching the build-in-public, the favor is small: drop a comment with your honest take. The harshest specific feedback wins a year of Pro.\n\nLink drops Wednesday.","mediaIds":[]}]}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'T-2 — pre-launch X thread (5 tweets)');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-78c6-bb00-5437a59f6172', p.id, NULL, 'draft', 'T-2 — pre-launch LinkedIn post', 'Three years of side-project work, one day of launch.

Wednesday I''m putting Tapeline on Product Hunt. It''s a body measurement journal — log weight + body dimensions + photos in 30 seconds a day, see what''s actually changing.

The honest reason it took 3 years: I shipped 4 versions, threw away 3, and the one I''m launching is the only one I''d want to use myself.

If you''ve been part of the journey — the testers, the brutal feedback, the "what if you tried X" — Wednesday is the day. I''ll post the link Wednesday morning IST.

Coffee shots welcome.', 'markdown', '{"seedSequence":2,"seedIntendedTime":"T-2 days, 9:00 AM CET","authorType":"person","visibility":"PUBLIC","postKind":"text"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'T-2 — pre-launch LinkedIn post');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-780a-9069-daeda99b7697', p.id, NULL, 'draft', 'Launch — X post 1 (the moment)', 'The thing I''ve been building for 3 years just went live on @ProductHunt 🥹

Tapeline: a 30-second-a-day body measurement journal. The bathroom scale doesn''t tell you if you lost fat or muscle — Tapeline does.

First comment is on PH 👇
[PH link]', 'markdown', '{"seedSequence":3,"seedIntendedTime":"T0, 12:01 AM PT","seedReferrerSlug":"ph_x","postKind":"tweet"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — X post 1 (the moment)');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-75b9-9a84-1cf8bfa29468', p.id, NULL, 'draft', 'Launch — X post 2 (Europe wakes up)', 'Tapeline is on Product Hunt today.

The pitch: stop trusting the scale. Log 10 body measurements + photos in 30s/day, see what''s actually changing.

7 hours in, [N] installs from PH, conversion looking decent.

[PH link]', 'markdown', '{"seedSequence":4,"seedIntendedTime":"T0, 6:00 AM PT","seedReferrerSlug":"ph_x","postKind":"tweet"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — X post 2 (Europe wakes up)');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-74be-8430-381fd8992001', p.id, NULL, 'draft', 'Launch — X post 3 (US wakes up)', '[N] hours into the @ProductHunt launch and Tapeline is at #[X] for the day. Comment thread has been gold — feature requests, bug reports, one user already at a 12-day streak.

Free to try, $5/mo for photo tracking. iOS + Android.

[PH link]', 'markdown', '{"seedSequence":5,"seedIntendedTime":"T0, 12:00 PM PT","seedReferrerSlug":"ph_x","postKind":"tweet"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — X post 3 (US wakes up)');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-7842-a0c7-067e1f4f726a', p.id, NULL, 'draft', 'Launch — X post 4 (closing out)', 'Closing out an exhausting day on PH. Whatever the rank turns out to be, the comments alone made it worth it.

If you tried Tapeline today — drop your honest take. Best feedback wins a free year of Pro.

[PH link]', 'markdown', '{"seedSequence":6,"seedIntendedTime":"T0, 5:00 PM PT","seedReferrerSlug":"ph_x","postKind":"tweet"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — X post 4 (closing out)');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-7c90-82f5-30265799beac', p.id, NULL, 'draft', 'Launch +1 — X results post', 'Day after PH:
- #[X] product of the day
- [N] installs, [M] paying
- The "harshest feedback wins Pro" thing surfaced 3 features I''m building this week

Big thanks to everyone who showed up. Onward.', 'markdown', '{"seedSequence":7,"seedIntendedTime":"T+1, 9:00 AM IST","seedReferrerSlug":"ph_x","postKind":"tweet"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch +1 — X results post');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-7646-95f9-46d2ca3c052f', p.id, NULL, 'draft', 'Launch — LinkedIn post', '3 years ago I started lifting weights and got annoyed that no app would track the *actual* changes — chest, waist, arms, hips. Just weight.

So I built one.

Tapeline launched on Product Hunt today. It''s a 30-second-a-day body journal: log 10 measurements + photos, then compare any two days side-by-side. iOS + Android, free to use, $5/mo for photo tracking.

The hardest part wasn''t the engineering — it was deciding what NOT to put in. No calorie tracking. No social feed. No "share your transformation". Just a quiet, private record of your body, week by week.

If that sounds like something you''d use, feedback is what makes a launch. Comment, install, gripe — all of it helps.

[PH link]', 'markdown', '{"seedSequence":8,"seedIntendedTime":"T0, 9:00 AM CET","seedReferrerSlug":"ph_linkedin","authorType":"person","visibility":"PUBLIC","postKind":"text"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — LinkedIn post');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-735c-b010-a1cc468c70ed', p.id, NULL, 'draft', 'I launched my body measurement app on Product Hunt today after 3 years of building', 'Hey r/SideProject 👋 — long-time lurker, finally shipping something I''ve been on for years.

Tapeline is a 30-second-a-day body measurement journal. I built it because I tried five fitness apps when I started lifting and hated all of them — they wanted my email before I could see anything, the UI felt like 2014, and none compared photos side-by-side.

Today''s the Product Hunt launch. Sharing here because /r/SideProject was huge in my early validation — half my first 100 users came from a single post here a year ago.

[PH link]

Free to try, $5/mo for photo + comparison features. iOS + Android.

Would love your honest take in the comments — that''s what moves PH and what helps me decide what to build next.', 'markdown', '{"seedSequence":9,"seedIntendedTime":"T0, soon after launch","seedReferrerSlug":"ph_reddit","postKind":"self","subreddit":"SideProject"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'I launched my body measurement app on Product Hunt today after 3 years of building');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-78fc-9874-09fb68b9bb43', p.id, NULL, 'draft', 'Launch — Instagram caption', '3 years of building, 1 day to launch.

Tapeline is now on @producthunt 🚀

The honest body tracker — measurements + photos, daily.
Link in bio.', 'markdown', '{"seedSequence":10,"seedIntendedTime":"T0, post launch","seedReferrerSlug":"ph_ig","postKind":"image","shareToFeed":true}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — Instagram caption');
INSERT INTO drafts (id, project_id, account_id, status, title, body, body_format, platform_options, created_by) SELECT '019e02b3-ec93-777d-8ccc-a1c34aad3340', p.id, NULL, 'draft', 'Launch — PH first comment (post within 60s of going live)', 'Hey Product Hunt 👋

I''m Sangeet, the maker of Tapeline.

Three years ago I started lifting weights and using a tape to measure my arms, chest, waist — the stuff a scale never tells you. I tried five tracking apps and hated all of them. They wanted my email before they''d let me see anything, they sold the data, the UX was a 2014 fitness-tracker time capsule, and none of them actually compared photos side-by-side.

So I built Tapeline. **It''s a 30-second-a-day body journal.** Log weight, 10 body dimensions, wellness scores, and (Pro) up to 3 progress photos. Then on any future date, you can compare any two days side-by-side — numbers + photos.

What''s different:
- **Your photos stay yours.** Private by default. Only you can see them. Delete your account → they''re gone within seconds.
- **Built for the daily 30 seconds, not the once-a-month splurge.** Onboarding is two taps. Logging is the dashboard, not a 6-step form.
- **Streaks + smart reminders.** Pick daily / weekly / biweekly, your timezone, your quiet hours. The app shuts up when you''re asleep.

What''s free: daily logging, calendar view, weight + 10 measurements, wellness scores, streaks, dashboard charts.
What''s Pro ($5/mo): photo upload, photo compare, CSV export.

I''d love feedback on **two specific things:**
1. Does the comparison view feel like the most honest mirror you''ve had, or just another chart?
2. The "30-second daily check-in" claim — does the onboarding actually deliver that on day one, or am I lying to myself?

📱 iOS: https://apps.apple.com/in/app/tapeline-body-tracker/id6762095383
📱 Android: https://play.google.com/store/apps/details?id=fit.measures.tapeline
🌐 Web: https://measures.fit

I''ll be in this thread all day — drop questions, gripes, feature requests. The harshest feedback wins a free year of Pro 🎯

— Sangeet', 'markdown', '{"seedSequence":11,"seedIntendedTime":"T0, within 60 seconds of going live"}', u.id FROM projects p JOIN users u ON u.email = 'sangeet.verma91@gmail.com' WHERE p.slug = 'tapeline'   AND NOT EXISTS (SELECT 1 FROM drafts d WHERE d.project_id = p.id AND d.title = 'Launch — PH first comment (post within 60s of going live)');

